### ISSUE TITLE
java.lang.String cannot be cast to java.lang.Double

### ISSUE THREAD

**Issue by NidhishVyas** [barakataboujreich/react-native-ble-advertise#4]
I am getting this error when i am trying to advertise my RN app

**Comment by barakataboujreich** [comment]
Can you share more details? 
A reproducable code that is causing the issue?

**Comment by NidhishVyas** [comment]
const startBLEAdvertising = async () => {
    const permissionsGranted = await requestPermissions()
    if (permissionsGranted) {
      const uuid = '44C13E43-097A-9C9F-537F-5666A6840C08'
      const major = '00001'
      const minor = '00003'
      try {
        BleAdvertise.setCompanyId('0x00e0')
        await BleAdvertise.broadcast(uuid, major, minor)
        console.log('Broadcast started')
        Alert.alert('Broadcast Started', 'Your device is now broadcasting as a peripheral')
      } catch (error) {
        console.log('Broadcast failed with: ' + error)
        Alert.alert('Broadcast Failed', `Failed to start broadcasting: ${error}`)
      }
    } else {
      console.log('Permissions not granted')
      Alert.alert('Permissions Denied', 'Necessary permissions are not granted')
    }
  }
  
  This is the code that i am using to advertise

**Comment by NidhishVyas** [comment]
const startBLEAdvertising = async () => {
    const permissionsGranted = await requestPermissions()
    if (permissionsGranted) {
      const uuid = '44C13E43-097A-9C9F-537F-5666A6840C08'
      const major = '00001'
      const minor = '00003'
      try {
        BleAdvertise.setCompanyId('0x00e0')
        await BleAdvertise.broadcast(uuid, major, minor)
        console.log('Broadcast started')
        Alert.alert('Broadcast Started', 'Your device is now broadcasting as a peripheral')
      } catch (error) {
        console.log('Broadcast failed with: ' + error)
        Alert.alert('Broadcast Failed', `Failed to start broadcasting: ${error}`)
      }
    } else {
      console.log('Permissions not granted')
      Alert.alert('Permissions Denied', 'Necessary permissions are not granted')
    }
  }
  
  This is the code that i am using to advertise

**Comment by barakataboujreich** [comment]
sorry we have an issue with the documentation, will fix it soon

the major and minor should be integer and companyid as hex as the following:

```
BleAdvertise.setCompanyId(0x00e0);
const major = parseInt("CD00", 16);
const minor = parseInt("0003", 16);
//if you have it in hex
//or just use integers
// const major = 400;
// const minor = 500;
```

make sure to request the proper permission
```
PermissionsAndroid.request(PermissionsAndroid.PERMISSIONS.BLUETOOTH_ADVERTISE);
```
