### ISSUE TITLE
Crash on ios when using any function

### ISSUE THREAD

**Issue by Starman3787** [barakataboujreich/react-native-ble-advertise#6]
I am new to react-native and react-native-ble-advertise, so I am probably doing something wrong, but would appreciate any help.

The app I am working on needs to advertise over bluetooth so a desktop app can detect the phone, connect to it, then communicate data, hence why I'm trying to use this module.

I've followed the steps outlined in the readme:

```
npm install react-native-ble-advertise
```

and since i'm trying to run this on ios:

```
cd ios
pod install
```

no errors were encountered here

then I import  and  use `react-native-ble-advertise` in my `app/App.tsx` as follows:

```tsx
import React from 'react';
import {
  Button,
  SafeAreaView,
  ScrollView,
  StatusBar,
  Text,
  useColorScheme,
  View,
} from 'react-native';
import '../global.css';
import { broadcast, setCompanyId } from 'react-native-ble-advertise';

const uuid = '44C13E43-097A-9C9F-537F-5666A6840C08';
const major = parseInt('CD00', 16);
const minor = parseInt('0003', 16);

import {
  Colors,
} from 'react-native/Libraries/NewAppScreen';

function App(): React.JSX.Element {
  const isDarkMode = useColorScheme() === 'dark';

  const backgroundStyle = {
    backgroundColor: isDarkMode ? Colors.darker : Colors.lighter,
  };

  return (
    <SafeAreaView style={backgroundStyle}>
      <StatusBar
        barStyle={isDarkMode ? 'light-content' : 'dark-content'}
        backgroundColor={backgroundStyle.backgroundColor}
      />
      <ScrollView
        contentInsetAdjustmentBehavior="automatic"
        style={backgroundStyle}>
        <View
          style={{
            backgroundColor: isDarkMode ? Colors.black : Colors.white,
          }}
          className="p-12">
          <Text className="text-5xl text-primary text-center font-bold">
            hello world
          </Text>
          <Text className="text-3xl text-secondary text-center font-bold italics">
            test app
          </Text>
          <Button
            title="set company id"
            onPress={() => {
              setCompanyId(0x00E0);
            }}
          />
          <Button
            title="advertise"
            onPress={() => {
              broadcast(uuid, major, minor)
                .then(success => {
                  console.log('broadcast started');
                })
                .catch(error => {
                  console.log('broadcast failed with: ' + error);
                });
            }}
          />
        </View>
      </ScrollView>
    </SafeAreaView>
  );
}

export default App;
```

the app can be built and run on my iphone with no issues

that is, until i click the "set company id" button or the "advertise" button. the app just crashes. 

i can't find an error unfortunately, since the debug console disconnects when the app crashes (if there is somewhere else i can look, please let me know - i'm new to this)

please let me know what i should try, or if i've missed any steps! thanks

**Comment by barakataboujreich** [comment]
hey there, can you please share which react native version you are using? and which ios are you testing on? and if you can share a complete project i can replicate the issue with?

**Comment by Starman3787** [comment]
hello, react native version `0.76.3`, ios `18.1.1` and i've made a public repo of the project https://github.com/Starman3787/react-native-bluetooth-debug (hopefully there is nothing in there that shouldn't be made public)

**Comment by barakataboujreich** [comment]
unfortunately this plugin is still not functioning on latest react native version due to the new architecture. the latest working version on react native is 0.74.6.

i am still working on a new version working for RN > 0.74

**Comment by Starman3787** [comment]
ah that makes sense. is there an eta of when this will be done? just wondering whether i should wait or try downgrading the react native version

**Comment by barakataboujreich** [comment]
a version working for RN new architecture is published. tested with RN 0.76
